//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTripV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_ALIAS_ALI
    {
        public decimal ALI_ID { get; set; }
        public decimal HOT_ID { get; set; }
        public string ALI_INTITULE { get; set; }
    
        public virtual T_E_HOTEL_HOT T_E_HOTEL_HOT { get; set; }
    }
}
