//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTripWebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_AVIS_AVI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_E_AVIS_AVI()
        {
            this.T_E_PHOTO_PHO = new HashSet<T_E_PHOTO_PHO>();
            this.T_J_STYLEAVIS_STA = new HashSet<T_J_STYLEAVIS_STA>();
            this.T_R_LIEUALENTOUR_LAL = new HashSet<T_R_LIEUALENTOUR_LAL>();
            this.T_E_ABONNE_ABO1 = new HashSet<T_E_ABONNE_ABO>();
        }
    
        public decimal AVI_ID { get; set; }
        public decimal ABO_ID { get; set; }
        public decimal HOT_ID { get; set; }
        public decimal VIS_ID { get; set; }
        public decimal PER_ID { get; set; }
        public Nullable<decimal> WIF_ID { get; set; }
        public decimal LNG_ID { get; set; }
        public System.DateTime AVI_DATE { get; set; }
        public string AVI_TITRE { get; set; }
        public string AVI_DETAIL { get; set; }
        public decimal AVI_NOTEGLOBALE { get; set; }
        public decimal AVI_NOTECHAMBRES { get; set; }
        public decimal AVI_NOTESERVICE { get; set; }
        public decimal AVI_NOTEPROPRETE { get; set; }
        public string AVI_CONSEIL { get; set; }
    
        public virtual T_E_ABONNE_ABO T_E_ABONNE_ABO { get; set; }
        public virtual T_E_HOTEL_HOT T_E_HOTEL_HOT { get; set; }
        public virtual T_R_TYPEVISITE_VIS T_R_TYPEVISITE_VIS { get; set; }
        public virtual T_R_WIFI_WIF T_R_WIFI_WIF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_E_PHOTO_PHO> T_E_PHOTO_PHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_J_STYLEAVIS_STA> T_J_STYLEAVIS_STA { get; set; }
        public virtual T_R_LANGUEAVIS_LNG T_R_LANGUEAVIS_LNG { get; set; }
        public virtual T_R_PERIODEVISITE_PER T_R_PERIODEVISITE_PER { get; set; }
        public virtual T_E_REPONSEAVIS_REP T_E_REPONSEAVIS_REP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_R_LIEUALENTOUR_LAL> T_R_LIEUALENTOUR_LAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_E_ABONNE_ABO> T_E_ABONNE_ABO1 { get; set; }
    }
}
